### ISSUE TITLE
Bug: Error when adding combatant

### ISSUE THREAD

**Issue by UnoriginalDM** [jessev14/floating-combat-toolbox#2]
Hello, I am getting a weird error when using the module in one of my worlds without having any other modules active. The world has been updated and been around since version 7.9. I have tried using the module on a fresh world and the error does NOT occur. I am hoping there is an easy solution to this if not I will look into importing everything from my old world into a fresh one.

I am currently on version 8.9 of foundry.

The error I get occurs whenever I add a token to the combat tracker.

foundry.js:197 TypeError: Cannot read properties of null (reading 'data')
    at helpers.js:5
    at Map.find (collection.mjs:46)
    at getTokenFromTokenID (helpers.js:2)
    at floating-combat-toolbox.js:91
    at Function._call (foundry.js:194)
    at Function.call (foundry.js:179)
    at ClientDatabaseBackend._preCreateDocumentArray (foundry.js:8687)
    at async ClientDatabaseBackend._createEmbeddedDocuments (foundry.js:8629)

Thank you in advance and I will you keep you updated if I figure out a solution.

**Comment by jessev14** [comment]
Can you select the token you're trying to add and then enter the following into the console:
`_token`
then right click the result and copy the object here?

**Comment by UnoriginalDM** [comment]
Hey sorry for the delay, but I think you fixed it with the update today. I am no longer getting the error!
