### ISSUE TITLE
Foundry version 9/1.5.3 multilevel tokens interaction broken again.

### ISSUE THREAD

**Issue by MatthewAMoseley** [jessev14/floating-combat-toolbox#3]
"Cloned tokens and the new Active Effects system" updated in the current versions of foundry and multilevel tokens. Tokens moving from one scene to another via multilevel token regions don't preserve initiative in multi-scene encounters (see attached screenshots for example), Manually copying tokens does seem to preserve initiative still though. Other bugs are open on that project at the moment which might be related but just making this issue known on your end.
![EncounterSetup](https://user-images.githubusercontent.com/9036193/168500373-2d365ca0-92f8-4529-a1ae-203a823e29a6.png)
.
![PostTeleportError](https://user-images.githubusercontent.com/9036193/168500376-2e5d9455-eef3-4255-a254-d18ef18b3ae6.png)

**Comment by jessev14** [comment]
If you're on Foundry version 9, this module is obsolete. There is a core feature to pin/unpin combats so that you can track combats across scenes.

**Comment by MatthewAMoseley** [comment]
Oh wow, I totally misunderstood that feature, also that's unfortunate. It seems significantly less versatile than this. Can't move actors across scenes like this with the built in functions at all. Thanks for the clarification though.
